version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: notabenoid
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build: .
    command: php -S 0.0.0.0:3000
    volumes:
      - .:/nota
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db

volumes:
  postgres:
